# -*- coding: utf-8 -*-
"""phase2b_final_corrections_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBOV30Su0TJcy-kya_zuWgdKCXFiAFie
"""

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
PROJECT_DIR = Path("/content/drive/MyDrive/CV-CW")        # the folder you used in phase 1
OUTPUT_DIR = PROJECT_DIR / "outputs"; FIG_DIR = OUTPUT_DIR / "figures"
WORKING_ZIP = PROJECT_DIR / "aptos_1024.zip"
for f in ["splits.csv", "image_quality.csv"]:
    print(f"{f:20s} found: {(OUTPUT_DIR / f).exists()}")
print("working copy found:", WORKING_ZIP.exists())

import zipfile, shutil
IMG_DIR = Path("/content/aptos_1024/images")
if any(IMG_DIR.glob("*.jpg")):
    print("Images already on disk")
elif WORKING_ZIP.exists():
    shutil.copy(WORKING_ZIP, "/content/aptos_1024.zip")
    with zipfile.ZipFile("/content/aptos_1024.zip") as z:
        z.extractall("/content/aptos_1024")
    print("Unpacked the working copy")
else:
    print("Working copy missing - run the next cell to rebuild it")
print("images on disk:", len(list(IMG_DIR.glob("*.jpg"))))

import json, random, time
import numpy as np, pandas as pd, cv2
import matplotlib.pyplot as plt
from concurrent.futures import ThreadPoolExecutor

SEED = 42
random.seed(SEED); np.random.seed(SEED)
SIZE = 300
CLASS_NAMES = ["No DR", "Mild NPDR", "Moderate NPDR", "Severe NPDR", "Proliferative DR"]

PREPROCESS_VARIANTS = {
    "P0_raw":           "FOV crop + square pad + resize (baseline)",
    "P1_clahe":         "P0 + CLAHE on the L channel of LAB (contrast adjustment)",
    "P2_clahe_unsharp": "P0 + median denoise + CLAHE + unsharp mask (contrast + edge enhancement)",
    "P3_ben_graham":    "P0 + Gaussian local-average subtraction (Graham, 2015)",
}
DEFAULT_VARIANT = "P2_clahe_unsharp"

# phase 1 also stored quality columns in splits.csv; keep only the four core columns here
splits = pd.read_csv(OUTPUT_DIR / "splits.csv")[["id", "path", "grade", "split"]]
splits["img"] = splits["id"].map(lambda i: str(IMG_DIR / f"{i}.jpg"))
missing = (~splits["img"].map(lambda p: Path(p).exists())).sum()
print("images listed:", len(splits), "| missing on disk:", missing)
quality = pd.read_csv(OUTPUT_DIR / "image_quality.csv")          # measured on the ORIGINAL photos
train = splits[splits.split == "train"].reset_index(drop=True)
print(splits["split"].value_counts().to_dict())

def load_rgb(path: str):
    """Read an image from disk as an RGB uint8 array."""
    bgr = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if bgr is None:
        raise FileNotFoundError(f"Could not read image: {path}")
    return cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)


def fov_mask(img: np.ndarray, tol: int = 10):
    """Binary mask of the circular field of view (pixels brighter than `tol`)."""
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    mask = (gray > tol).astype(np.uint8)
    # Morphological opening removes isolated bright specks in the border.
    return cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))


def crop_fov(img: np.ndarray, tol: int = 10):
    """Crop the black border so the retina touches the image edges."""
    mask = fov_mask(img, tol)
    ys, xs = np.where(mask > 0)
    if len(xs) < 0.05 * mask.size:      # almost-black image: do not crop
        return img
    return img[ys.min(): ys.max() + 1, xs.min(): xs.max() + 1]


def pad_to_square(img: np.ndarray):
    """Pad with black so width == height (keeps the retina circular)."""
    h, w = img.shape[:2]
    side = max(h, w)
    top, left = (side - h) // 2, (side - w) // 2
    return cv2.copyMakeBorder(img, top, side - h - top, left, side - w - left,
                              cv2.BORDER_CONSTANT, value=(0, 0, 0))


def circular_mask(img: np.ndarray, scale: float = 0.96):
    """Black out everything outside a centred circle (removes enhancement halo)."""
    h, w = img.shape[:2]
    mask = np.zeros((h, w), np.uint8)
    cv2.circle(mask, (w // 2, h // 2), int(min(h, w) / 2 * scale), 1, -1)
    return img * mask[..., None]

def clahe_lab(img: np.ndarray, clip: float = 2.0, grid: int = 8):
    """CLAHE on lightness only, so diagnostic colour is preserved."""
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    l = cv2.createCLAHE(clipLimit=clip, tileGridSize=(grid, grid)).apply(l)
    return cv2.cvtColor(cv2.merge((l, a, b)), cv2.COLOR_LAB2RGB)


def unsharp_mask(img: np.ndarray, sigma: float = 2.0, amount: float = 1.0):
    """Edge enhancement: img + amount * (img - blurred)."""
    blurred = cv2.GaussianBlur(img, (0, 0), sigma)
    return cv2.addWeighted(img, 1 + amount, blurred, -amount, 0)


def ben_graham(img: np.ndarray, sigma_ratio: float = 30.0):
    """Subtract the local average colour (Graham, 2015).

    4*I - 4*Gaussian(I) + 128 removes slow illumination changes between
    cameras and leaves lesions and vessels on a neutral grey background.
    """
    sigma = img.shape[0] / sigma_ratio
    return cv2.addWeighted(img, 4, cv2.GaussianBlur(img, (0, 0), sigma), -4, 128)


def preprocess(img: np.ndarray, variant: str = DEFAULT_VARIANT,
               size: int = 300):
    """Apply one named pre-processing variant and return a size x size RGB image."""
    if variant not in PREPROCESS_VARIANTS:
        raise ValueError(f"Unknown variant {variant}")
    out = pad_to_square(crop_fov(img))
    out = cv2.resize(out, (size, size), interpolation=cv2.INTER_AREA)

    if variant == "P1_clahe":
        out = clahe_lab(out)
    elif variant == "P2_clahe_unsharp":
        out = cv2.medianBlur(out, 3)
        out = clahe_lab(out)
        out = unsharp_mask(out)
    elif variant == "P3_ben_graham":
        out = ben_graham(out)
    return circular_mask(out)


def pipeline_stages(img: np.ndarray, size: int = 300):
    """Every intermediate stage of P2, used to draw the step-by-step figure."""
    cropped = crop_fov(img)
    squared = pad_to_square(cropped)
    resized = cv2.resize(squared, (size, size), interpolation=cv2.INTER_AREA)
    denoised = cv2.medianBlur(resized, 3)
    clahe = clahe_lab(denoised)
    sharp = unsharp_mask(clahe)
    return {
        "1. Original": img,
        "2. FOV crop": cropped,
        "3. Pad + resize": resized,
        "4. Median denoise": denoised,
        "5. CLAHE (L channel)": clahe,
        "6. Unsharp mask": sharp,
        "7. Circular mask": circular_mask(sharp),
    }

def optic_disc_centre(img):
    """The optic disc is the brightest LARGE bright region. Blurring with a width
    close to the disc radius averages away small bright lesions (exudates), so the
    brightest point of the blurred lightness image is the disc centre."""
    light = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)[..., 0].astype(np.float32)
    light[img.max(2) <= 10] = 0
    blurred = cv2.GaussianBlur(light, (0, 0), img.shape[0] / 14)
    return np.unravel_index(np.argmax(blurred), blurred.shape)

def detail_patch(img, win=70):
    """Top-left corner of the window with the most edge energy, away from the optic disc."""
    green = img[..., 1].astype(np.float32)
    energy = cv2.boxFilter(np.abs(cv2.Laplacian(green, cv2.CV_32F)), -1, (win, win), normalize=False)
    dy, dx = optic_disc_centre(img)
    yy, xx = np.mgrid[:img.shape[0], :img.shape[1]]
    near_disc = (yy - dy) ** 2 + (xx - dx) ** 2 < (img.shape[0] / 14 + win / 2 + 5) ** 2
    inside = cv2.erode((img.max(2) > 10).astype(np.uint8), np.ones((win, win), np.uint8))
    energy[near_disc | (inside == 0)] = 0
    cy, cx = np.unravel_index(np.argmax(energy), energy.shape)
    return max(cy - win // 2, 0), max(cx - win // 2, 0)

MANUAL_PATCH = None     # e.g. (120, 60) to choose the region yourself as (row, column)

sev = train[train.grade >= 3].sample(1, random_state=SEED).iloc[0]
raw_sev = load_rgb(sev["img"])
before, after = preprocess(raw_sev, "P0_raw", SIZE), preprocess(raw_sev, "P2_clahe_unsharp", SIZE)
y, x = MANUAL_PATCH or detail_patch(after); W = 70

fig, axes = plt.subplots(1, 4, figsize=(14, 3.8))
for ax, im, t in [(axes[0], before, "P0 full image"), (axes[1], before[y:y+W, x:x+W], "P0 close-up"),
                  (axes[2], after[y:y+W, x:x+W], "P2 close-up"), (axes[3], after, "P2 full image")]:
    ax.imshow(im, interpolation="nearest"); ax.set_title(t, fontsize=10); ax.axis("off")
for ax in (axes[0], axes[3]):
    ax.add_patch(plt.Rectangle((x, y), W, W, fill=False, ec="yellow", lw=1.5))
fig.suptitle(f"Image {sev['id']} (grade {sev['grade']}): region with the most detail", fontsize=10)
fig.tight_layout(); fig.savefig(FIG_DIR / "preprocessing_closeup.png", dpi=150); plt.show()

"""creates an image-quality filter that rejects photos that are too poor to grade reliably, while checking that it does not unfairly reject any disease grade."""

def fit_quality_thresholds(metrics: pd.DataFrame, pct: float = 1.0):
    """Data-driven thresholds: an image is flagged if it is worse than the
    `pct`-th percentile of the TRAINING set on any metric. Using percentiles
    avoids hand-picked magic numbers and adapts to whichever dataset is used.

    Only measures where "lower is worse" are used (decision D20):
      * fov_ratio was removed: its lowest values belonged to well-framed photos
        from one camera whose circle has a small notch.
      * a "too bright" upper limit on mean brightness was removed: the photos
        it refused were bright but clearly gradable. Over-exposure means
        washed-out regions, not a bright average.
    """
    return {
        "sharpness_min": float(np.percentile(metrics["sharpness"], pct)),
        "brightness_min": float(np.percentile(metrics["brightness"], pct)),
        "contrast_min": float(np.percentile(metrics["contrast"], pct)),
    }

qs = splits.merge(quality[["id", "sharpness", "brightness", "contrast", "fov_ratio"]], on="id")
thr = fit_quality_thresholds(qs[qs.split == "train"])
json.dump(thr, open(OUTPUT_DIR / "quality_thresholds.json", "w"), indent=2)
print(json.dumps(thr, indent=2))

checks = {
    "blurred":       qs.sharpness < thr["sharpness_min"],
    "too dark":      qs.brightness < thr["brightness_min"],
    "low contrast":  qs.contrast < thr["contrast_min"],
}
for name, mask in checks.items(): qs[name] = mask
qs["refused"] = np.any(np.column_stack(list(checks.values())), axis=1)

by_split = qs.groupby("split")[["refused", *checks]].mean().mul(100).round(1)
by_grade = (qs.groupby(qs.grade.map(lambda g: CLASS_NAMES[g]))["refused"].mean()
            .reindex(CLASS_NAMES).mul(100).round(1))
rates = pd.concat({"by split (%)": by_split["refused"], "by grade (%)": by_grade})
rates.to_csv(OUTPUT_DIR / "quality_gate_rates.csv")
display(by_split); display(by_grade.to_frame("refused (%)"))

fig, axes = plt.subplots(len(checks), 3, figsize=(8, 2.8 * len(checks)), squeeze=False)
for r, name in enumerate(checks):
    hits = qs[qs[name]].sample(min(3, int(qs[name].sum())), random_state=SEED) if qs[name].any() else qs.head(0)
    for c in range(3):
        ax = axes[r, c]; ax.axis("off")
        if c < len(hits):
            ax.imshow(cv2.resize(load_rgb(hits.iloc[c]["img"]), (256, 256)))
            ax.set_title(f"grade {hits.iloc[c]['grade']}", fontsize=8)
    axes[r, 0].text(-0.15, 0.5, name, transform=axes[r, 0].transAxes, rotation=90, va="center", ha="right")
fig.suptitle("Photos the quality gate would refuse, by reason", fontsize=11)
fig.tight_layout(); fig.savefig(FIG_DIR / "quality_gate_examples.png", dpi=130); plt.show()