# -*- coding: utf-8 -*-
"""phase4b_training_evidence_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Og1RGq9rLcGJhZIi7Jf4SW3WZopJGZKb
"""

from google.colab import drive
drive.mount("/content/drive")
from pathlib import Path
import json
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image, display

PROJECT_DIR = Path("/content/drive/MyDrive/CV-CW")
OUTPUT_DIR = PROJECT_DIR / "outputs"; FIG_DIR = OUTPUT_DIR / "figures"; RUNS_DIR = OUTPUT_DIR / "runs"
exp = pd.read_csv(OUTPUT_DIR / "experiments.csv").drop_duplicates("run_name", keep="last")
show = ["run_name", "backbone", "variant", "augmentation", "balance", "lr_ft", "unfreeze", "dropout",
        "val_qwk", "val_qwk_ci_low", "val_qwk_ci_high", "val_macro_f1", "val_accuracy",
        "train_val_acc_gap", "best_epoch", "epochs_run", "train_minutes", "ms_per_image"]
show = [c for c in show if c in exp.columns]
display(exp[show].sort_values("val_qwk", ascending=False).reset_index(drop=True))
print(f"{len(exp)} runs recorded")

"""Each graph shows loss, accuracy, and validation QWK, with a dashed line marking the start of fine-tuning."""

for name in exp.sort_values("val_qwk", ascending=False).run_name:
    curves = RUNS_DIR / name / "curves.png"
    if curves.exists():
        print(f"=== {name} ===")
        display(Image(str(curves), width=1000))

"""A single graph compares validation QWK across all runs, showing which configurations improve faster, plateau, or keep improving."""

fig, ax = plt.subplots(figsize=(11, 5))
for name in exp.sort_values("val_qwk", ascending=False).run_name:
    hist_file = RUNS_DIR / name / "history.json"
    if not hist_file.exists():
        continue
    qwk = json.load(open(hist_file)).get("val_qwk", [])
    best = exp.set_index("run_name").loc[name, "val_qwk"]
    ax.plot(range(1, len(qwk) + 1), qwk, label=f"{name} ({best:.3f})", lw=1.6)
ax.set(xlabel="epoch", ylabel="validation QWK", title="Validation QWK per epoch, every run")
ax.legend(fontsize=7, ncol=2, loc="lower right"); ax.grid(alpha=0.3)
fig.tight_layout(); fig.savefig(FIG_DIR / "training_curves_all.png", dpi=150); plt.show()

"""The log.csv shows each epoch’s results, including learning-rate changes and when early stopping ended training."""

RUN = exp.sort_values("val_qwk", ascending=False).run_name.iloc[0]
log = pd.read_csv(RUNS_DIR / RUN / "log.csv")
print(f"{RUN}: {len(log)} epochs logged")
display(log.round(4))
print(json.dumps(json.load(open(RUNS_DIR / RUN / "meta.json")), indent=2)[:1200])