# -*- coding: utf-8 -*-
"""phase2_preprocessing_colab-updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12XbWVvtAyK9LrKq0-UwwBMKkmcgHknjx

Image pre-processing

Connect Google Drive and load the phase 1 results
"""

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
PROJECT_DIR = Path("/content/drive/MyDrive/CV-CW")
OUTPUT_DIR = PROJECT_DIR / "outputs"; FIG_DIR = OUTPUT_DIR / "figures"
WORKING_ZIP = PROJECT_DIR / "aptos_1024.zip"
for f in ["splits.csv", "image_quality.csv"]:
    print(f"{f:20s} found: {(OUTPUT_DIR / f).exists()}")
print("working copy found:", WORKING_ZIP.exists())

"""Get the images"""

import zipfile, shutil
IMG_DIR = Path("/content/aptos_1024/images")
if any(IMG_DIR.glob("*.jpg")):
    print("Images already on disk")
elif WORKING_ZIP.exists():
    shutil.copy(WORKING_ZIP, "/content/aptos_1024.zip")
    with zipfile.ZipFile("/content/aptos_1024.zip") as z:
        z.extractall("/content/aptos_1024")
    print("Unpacked the working copy")
else:
    print("Working copy missing - run the next cell to rebuild it")
print("images on disk:", len(list(IMG_DIR.glob("*.jpg"))))

"""setting images"""

import json, random, time
import numpy as np, pandas as pd, cv2
import matplotlib.pyplot as plt
from concurrent.futures import ThreadPoolExecutor

SEED = 42
random.seed(SEED); np.random.seed(SEED)
SIZE = 300
CLASS_NAMES = ["No DR", "Mild NPDR", "Moderate NPDR", "Severe NPDR", "Proliferative DR"]

PREPROCESS_VARIANTS = {
    "P0_raw":           "FOV crop + square pad + resize (baseline)",
    "P1_clahe":         "P0 + CLAHE on the L channel of LAB (contrast adjustment)",
    "P2_clahe_unsharp": "P0 + median denoise + CLAHE + unsharp mask (contrast + edge enhancement)",
    "P3_ben_graham":    "P0 + Gaussian local-average subtraction (Graham, 2015)",
}
DEFAULT_VARIANT = "P2_clahe_unsharp"

# phase 1 also stored quality columns in splits.csv. keeping only the four core columns here
splits = pd.read_csv(OUTPUT_DIR / "splits.csv")[["id", "path", "grade", "split"]]
splits["img"] = splits["id"].map(lambda i: str(IMG_DIR / f"{i}.jpg"))
missing = (~splits["img"].map(lambda p: Path(p).exists())).sum()
print("images listed:", len(splits), "| missing on disk:", missing)
quality = pd.read_csv(OUTPUT_DIR / "image_quality.csv")          # measured on the ORIGINAL photos
train = splits[splits.split == "train"].reset_index(drop=True)
print(splits["split"].value_counts().to_dict())

"""The pipeline building"""

def load_rgb(path: str):
    """Read an image from disk as an RGB uint8 array."""
    bgr = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if bgr is None:
        raise FileNotFoundError(f"Could not read image: {path}")
    return cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)


def fov_mask(img: np.ndarray, tol: int = 10):
    """Binary mask of the circular field of view (pixels brighter than `tol`)."""
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    mask = (gray > tol).astype(np.uint8)
    # Morphological opening removes isolated bright specks in the border.
    return cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))


def crop_fov(img: np.ndarray, tol: int = 10):
    """Crop the black border so the retina touches the image edges."""
    mask = fov_mask(img, tol)
    ys, xs = np.where(mask > 0)
    if len(xs) < 0.05 * mask.size:      # almost black image - do not crop
        return img
    return img[ys.min(): ys.max() + 1, xs.min(): xs.max() + 1]


def pad_to_square(img: np.ndarray):
    """Pad with black so width == height (keeps the retina circular)."""
    h, w = img.shape[:2]
    side = max(h, w)
    top, left = (side - h) // 2, (side - w) // 2
    return cv2.copyMakeBorder(img, top, side - h - top, left, side - w - left,
                              cv2.BORDER_CONSTANT, value=(0, 0, 0))


def circular_mask(img: np.ndarray, scale: float = 0.96):
    """Black out everything outside a centred circle (removes enhancement halo)."""
    h, w = img.shape[:2]
    mask = np.zeros((h, w), np.uint8)
    cv2.circle(mask, (w // 2, h // 2), int(min(h, w) / 2 * scale), 1, -1)
    return img * mask[..., None]

def clahe_lab(img: np.ndarray, clip: float = 2.0, grid: int = 8):
    """CLAHE on lightness only, so diagnostic colour is preserved."""
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    l = cv2.createCLAHE(clipLimit=clip, tileGridSize=(grid, grid)).apply(l)
    return cv2.cvtColor(cv2.merge((l, a, b)), cv2.COLOR_LAB2RGB)


def unsharp_mask(img: np.ndarray, sigma: float = 2.0, amount: float = 1.0):
    """Edge enhancement: img + amount * (img - blurred)."""
    blurred = cv2.GaussianBlur(img, (0, 0), sigma)
    return cv2.addWeighted(img, 1 + amount, blurred, -amount, 0)


def ben_graham(img: np.ndarray, sigma_ratio: float = 30.0):
    """Subtract the local average colour (Graham, 2015).

    4*I - 4*Gaussian(I) + 128 removes slow illumination changes between
    cameras and leaves lesions and vessels on a neutral grey background.
    """
    sigma = img.shape[0] / sigma_ratio
    return cv2.addWeighted(img, 4, cv2.GaussianBlur(img, (0, 0), sigma), -4, 128)


def preprocess(img: np.ndarray, variant: str = DEFAULT_VARIANT,
               size: int = 300):
    """Apply one named pre-processing variant and return a size x size RGB image."""
    if variant not in PREPROCESS_VARIANTS:
        raise ValueError(f"Unknown variant {variant}")
    out = pad_to_square(crop_fov(img))
    out = cv2.resize(out, (size, size), interpolation=cv2.INTER_AREA)

    if variant == "P1_clahe":
        out = clahe_lab(out)
    elif variant == "P2_clahe_unsharp":
        out = cv2.medianBlur(out, 3)
        out = clahe_lab(out)
        out = unsharp_mask(out)
    elif variant == "P3_ben_graham":
        out = ben_graham(out)
    return circular_mask(out)


def pipeline_stages(img: np.ndarray, size: int = 300):
    """Every intermediate stage of P2, used to draw the step-by-step figure."""
    cropped = crop_fov(img)
    squared = pad_to_square(cropped)
    resized = cv2.resize(squared, (size, size), interpolation=cv2.INTER_AREA)
    denoised = cv2.medianBlur(resized, 3)
    clahe = clahe_lab(denoised)
    sharp = unsharp_mask(clahe)
    return {
        "1. Original": img,
        "2. FOV crop": cropped,
        "3. Pad + resize": resized,
        "4. Median denoise": denoised,
        "5. CLAHE (L channel)": clahe,
        "6. Unsharp mask": sharp,
        "7. Circular mask": circular_mask(sharp),
    }

"""A Moderate NPDR training image with typical (median) sharpness, so the figure is
representative rather than hand-picked.
"""

q = train.merge(quality[["id", "sharpness"]], on="id")
mod = q[q.grade == 2]
example = mod.iloc[(mod.sharpness - mod.sharpness.median()).abs().argsort().iloc[0]]
raw = load_rgb(example["img"])
stages = pipeline_stages(raw, SIZE)

fig, axes = plt.subplots(1, len(stages), figsize=(2.6 * len(stages), 3))
for ax, (title, im) in zip(axes, stages.items()):
    ax.imshow(im); ax.set_title(title, fontsize=9); ax.axis("off")
fig.suptitle(f"P2 pipeline on image {example['id']} (grade 2)", fontsize=10)
fig.tight_layout(); fig.savefig(FIG_DIR / "preprocessing_stages.png", dpi=150); plt.show()

"""check with contrast and edge enhancement"""

def optic_disc_centre(img):
    """The optic disc is the brightest LARGE bright region. Blurring with a width
    close to the disc radius averages away small bright lesions (exudates), so the
    brightest point of the blurred lightness image is the disc centre."""
    light = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)[..., 0].astype(np.float32)
    light[img.max(2) <= 10] = 0
    blurred = cv2.GaussianBlur(light, (0, 0), img.shape[0] / 14)
    return np.unravel_index(np.argmax(blurred), blurred.shape)

def detail_patch(img, win=70):
    """Top-left corner of the window with the most edge energy, away from the optic disc."""
    green = img[..., 1].astype(np.float32)
    energy = cv2.boxFilter(np.abs(cv2.Laplacian(green, cv2.CV_32F)), -1, (win, win), normalize=False)
    dy, dx = optic_disc_centre(img)
    yy, xx = np.mgrid[:img.shape[0], :img.shape[1]]
    near_disc = (yy - dy) ** 2 + (xx - dx) ** 2 < (img.shape[0] / 14 + win / 2 + 5) ** 2
    inside = cv2.erode((img.max(2) > 10).astype(np.uint8), np.ones((win, win), np.uint8))
    energy[near_disc | (inside == 0)] = 0
    cy, cx = np.unravel_index(np.argmax(energy), energy.shape)
    return max(cy - win // 2, 0), max(cx - win // 2, 0)

MANUAL_PATCH = None     # e.g. (120, 60) to choose the region yourself as (row, column)

sev = train[train.grade >= 3].sample(1, random_state=SEED).iloc[0]
raw_sev = load_rgb(sev["img"])
before, after = preprocess(raw_sev, "P0_raw", SIZE), preprocess(raw_sev, "P2_clahe_unsharp", SIZE)
y, x = MANUAL_PATCH or detail_patch(after); W = 70

fig, axes = plt.subplots(1, 4, figsize=(14, 3.8))
for ax, im, t in [(axes[0], before, "P0 full image"), (axes[1], before[y:y+W, x:x+W], "P0 close-up"),
                  (axes[2], after[y:y+W, x:x+W], "P2 close-up"), (axes[3], after, "P2 full image")]:
    ax.imshow(im, interpolation="nearest"); ax.set_title(t, fontsize=10); ax.axis("off")
for ax in (axes[0], axes[3]):
    ax.add_patch(plt.Rectangle((x, y), W, W, fill=False, ec="yellow", lw=1.5))
dy, dx = optic_disc_centre(after)
axes[3].plot(dx, dy, "c+", ms=14, mew=2)                     # where the disc was found
fig.suptitle(f"Image {sev['id']} (grade {sev['grade']}): region with most detail "
             "(cyan + = detected optic disc, excluded)", fontsize=10)
fig.tight_layout(); fig.savefig(FIG_DIR / "preprocessing_closeup.png", dpi=150); plt.show()

"""Test with four different image processing methods to improve contrast and edges.
Compre the histogrames visually
"""

picks = train.groupby("grade").sample(1, random_state=SEED).sort_values("grade")
variants = list(PREPROCESS_VARIANTS)
fig, axes = plt.subplots(len(picks), len(variants), figsize=(3 * len(variants), 3 * len(picks)))
for r, (_, row) in enumerate(picks.iterrows()):
    im = load_rgb(row["img"])
    for c, v in enumerate(variants):
        axes[r, c].imshow(preprocess(im, v, SIZE)); axes[r, c].set_xticks([]); axes[r, c].set_yticks([])
        if r == 0: axes[r, c].set_title(v, fontsize=10)
    axes[r, 0].set_ylabel(CLASS_NAMES[row["grade"]], fontsize=10)
fig.tight_layout(); fig.savefig(FIG_DIR / "preprocessing_variants.png", dpi=120); plt.show()

before_img, after_img = stages["3. Pad + resize"], stages["7. Circular mask"]
fig, axes = plt.subplots(1, 2, figsize=(11, 3.4), sharey=True)
for ax, im, t in [(axes[0], before_img, "Before (resized only)"), (axes[1], after_img, "After P2")]:
    g = im[..., 1][im.max(2) > 10]
    ax.hist(g, bins=64, range=(0, 255), color="#2e7d32")
    ax.set(title=f"{t}: green channel, std = {g.std():.1f}", xlabel="intensity", ylabel="pixels")
fig.tight_layout(); fig.savefig(FIG_DIR / "preprocessing_histograms.png", dpi=150); plt.show()

"""Check different contrast and sharpening strengths to find the settings that make details clearer without adding noise, halos, or fake lesions."""

base = cv2.medianBlur(before, 3)
clips = [1.0, 2.0, 4.0, 8.0]; amounts = [0.0, 0.5, 1.0, 2.0]
fig, axes = plt.subplots(2, 4, figsize=(12, 6.4))
for ax, c in zip(axes[0], clips):
    ax.imshow(clahe_lab(base, clip=c)[y:y+W, x:x+W], interpolation="nearest")
    ax.set_title(f"CLAHE clip = {c}" + ("  (chosen)" if c == 2.0 else ""), fontsize=10); ax.axis("off")
for ax, a in zip(axes[1], amounts):
    ax.imshow(unsharp_mask(clahe_lab(base), amount=a)[y:y+W, x:x+W], interpolation="nearest")
    ax.set_title(f"unsharp amount = {a}" + ("  (chosen)" if a == 1.0 else ""), fontsize=10); ax.axis("off")
fig.suptitle("Parameter sensitivity on the close-up region", fontsize=11)
fig.tight_layout(); fig.savefig(FIG_DIR / "preprocessing_parameters.png", dpi=150); plt.show()

"""Measuring the effect on the whole dataset"""

def quality_metrics(img: np.ndarray):
    """Cheap, interpretable quality measures computed inside the field of view.

    sharpness  variance of the Laplacian of the green channel (low = blurred)
    brightness mean V (HSV) inside the FOV       (low = under-exposed)
    contrast   std of the green channel in FOV   (low = washed out)
    fov_ratio  share of the retina's bounding box that is retina: about 0.785
               (pi/4) for a complete circle, rising towards 1.0 when the camera
               cut the circle off; unusually low = irregular or partial retina
    The green channel is used because vessels and lesions have the highest
    contrast there. The cropped retina is resized straight to 512x512 (no
    padding) - exactly as in the phase 1 audit, so thresholds fitted on the
    phase 1 measurements apply unchanged to new photos in the app.
    """
    small = cv2.resize(crop_fov(img), (512, 512), interpolation=cv2.INTER_AREA)
    mask = fov_mask(small).astype(bool)
    if mask.sum() < 100:
        return {"sharpness": 0.0, "brightness": 0.0, "contrast": 0.0, "fov_ratio": 0.0}
    green = small[..., 1]
    lap = cv2.Laplacian(green, cv2.CV_64F)
    hsv = cv2.cvtColor(small, cv2.COLOR_RGB2HSV)
    return {
        "sharpness": float(lap[mask].var()),
        "brightness": float(hsv[..., 2][mask].mean()),
        "contrast": float(green[mask].std()),
        "fov_ratio": float(mask.mean()),
    }

sample = pd.concat([g.sample(min(100, len(g)), random_state=SEED)
                    for _, g in train.groupby("grade")]).reset_index(drop=True)
raws = [load_rgb(p) for p in sample["img"]]
print(f"Sample: {len(sample)} training images", sample.grade.value_counts().sort_index().to_dict())

rows, per_image = [], []
for v in variants:
    t0 = time.perf_counter()
    processed = [preprocess(im, v, SIZE) for im in raws]
    ms = (time.perf_counter() - t0) / len(raws) * 1000
    m = pd.DataFrame([quality_metrics(im) for im in processed]).assign(grade=sample.grade.values, variant=v)
    per_image.append(m)
    healthy, diseased = m[m.grade == 0].sharpness.median(), m[m.grade > 0].sharpness.median()
    rows.append({"variant": v, "brightness_spread": m.brightness.std(), "mean_contrast": m.contrast.mean(),
                 "sharpness_gap": healthy / diseased, "ms_per_image": ms})
metrics = pd.DataFrame(rows).round(3)
metrics.to_csv(OUTPUT_DIR / "preprocessing_metrics.csv", index=False)
display(metrics)

per_image = pd.concat(per_image)
fig, axes = plt.subplots(1, 2, figsize=(13, 4))
per_image.boxplot(column="brightness", by="variant", ax=axes[0])
axes[0].set(title="Brightness across images (tighter box = more consistent)", xlabel="", ylabel="brightness")
comp = per_image[per_image.variant.isin(["P0_raw", DEFAULT_VARIANT])]
for i, v in enumerate(["P0_raw", DEFAULT_VARIANT]):
    med = comp[comp.variant == v].groupby("grade").sharpness.median()
    axes[1].plot(med.index, med.values, "o-", label=v)
axes[1].set(title="Median sharpness per grade (flatter line = weaker shortcut)", xlabel="grade",
            ylabel="sharpness", xticks=range(5))
axes[1].legend(); fig.suptitle("")
fig.tight_layout(); fig.savefig(FIG_DIR / "preprocessing_standardisation.png", dpi=150); plt.show()

"""Checks whether image size is related to the eye disease grade, so the model does not use image size as a shortcut instead of learning the actual eye condition."""

from scipy.stats import chi2_contingency
sizes = splits.merge(quality[["id", "width", "height"]], on="id")
sizes["resolution"] = sizes["width"].astype(str) + "x" + sizes["height"].astype(str)
top = sizes["resolution"].value_counts().head(8).index
res_table = (sizes[sizes.resolution.isin(top)].groupby("resolution")
             .agg(images=("id", "size"), no_dr_share=("grade", lambda g: (g == 0).mean()),
                  mean_grade=("grade", "mean"))
             .sort_values("images", ascending=False).round(3))
res_table.to_csv(OUTPUT_DIR / "resolution_vs_grade.csv")
display(res_table)

ct = pd.crosstab(sizes["resolution"], sizes["grade"])
print(f"Overall No DR share: {(sizes.grade == 0).mean():.3f} | distinct resolutions: {len(ct)}")
if min(ct.shape) > 1:
    chi2 = chi2_contingency(ct)[0]
    cramers_v = np.sqrt(chi2 / (ct.values.sum() * (min(ct.shape) - 1)))
    print(f"Cramér's V between resolution and grade: {cramers_v:.3f}")
else:
    print("Only one resolution present - no size shortcut possible")

"""Check all images are scaled in the same way as the pretrained models expect"""

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406]); IMAGENET_STD = np.array([0.229, 0.224, 0.225])
img = after_img.astype(np.float32); inside = img.max(2) > 10
scaled = img / 255.0
standardised = (scaled - IMAGENET_MEAN) / IMAGENET_STD
report = pd.DataFrame({
    "stage": ["pre-processed (uint8)", "÷ 255", "ImageNet standardised"],
    "min": [img.min(), scaled.min(), standardised.min()],
    "max": [img.max(), scaled.max(), standardised.max()],
    "mean R/G/B inside retina": [np.round(x[inside].mean(0), 3) for x in (img, scaled, standardised)],
})
display(report)

"""Checks whether a photo is good enough to grade reliably, while making sure the quality filter does not unfairly reject images from any disease grade."""

def fit_quality_thresholds(metrics: pd.DataFrame, pct: float = 1.0):
    """Data-driven thresholds: an image is flagged if it is worse than the
    `pct`-th percentile of the TRAINING set on any metric (or brighter than the
    100-pct percentile for over-exposure). Using percentiles avoids hand-picked
    magic numbers and adapts to whichever dataset is used.

    fov_ratio is deliberately NOT used: on APTOS its lowest values belong to
    well-framed photos from one camera whose circle has a small notch, so a
    fov_ratio threshold rejected a camera type rather than bad framing
    (phase 2 evidence, decision D20)."""
    return {
        "sharpness_min": float(np.percentile(metrics["sharpness"], pct)),
        "brightness_min": float(np.percentile(metrics["brightness"], pct)),
        "brightness_max": float(np.percentile(metrics["brightness"], 100 - pct)),
        "contrast_min": float(np.percentile(metrics["contrast"], pct)),
    }

qs = splits.merge(quality[["id", "sharpness", "brightness", "contrast", "fov_ratio"]], on="id")
thr = fit_quality_thresholds(qs[qs.split == "train"])
json.dump(thr, open(OUTPUT_DIR / "quality_thresholds.json", "w"), indent=2)
print(json.dumps(thr, indent=2))

checks = {
    "blurred":       qs.sharpness < thr["sharpness_min"],
    "too dark":      qs.brightness < thr["brightness_min"],
    "too bright":    qs.brightness > thr["brightness_max"],
    "low contrast":  qs.contrast < thr["contrast_min"],
}
for name, mask in checks.items(): qs[name] = mask
qs["refused"] = np.any(np.column_stack(list(checks.values())), axis=1)

by_split = qs.groupby("split")[["refused", *checks]].mean().mul(100).round(1)
by_grade = (qs.groupby(qs.grade.map(lambda g: CLASS_NAMES[g]))["refused"].mean()
            .reindex(CLASS_NAMES).mul(100).round(1))
rates = pd.concat({"by split (%)": by_split["refused"], "by grade (%)": by_grade})
rates.to_csv(OUTPUT_DIR / "quality_gate_rates.csv")
display(by_split); display(by_grade.to_frame("refused (%)"))

fig, axes = plt.subplots(len(checks), 3, figsize=(8, 2.8 * len(checks)), squeeze=False)
for r, name in enumerate(checks):
    hits = qs[qs[name]].sample(min(3, int(qs[name].sum())), random_state=SEED) if qs[name].any() else qs.head(0)
    for c in range(3):
        ax = axes[r, c]; ax.axis("off")
        if c < len(hits):
            ax.imshow(cv2.resize(load_rgb(hits.iloc[c]["img"]), (256, 256)))
            ax.set_title(f"grade {hits.iloc[c]['grade']}", fontsize=8)
    axes[r, 0].text(-0.15, 0.5, name, transform=axes[r, 0].transAxes, rotation=90, va="center", ha="right")
fig.suptitle("Photos the quality gate would refuse, by reason", fontsize=11)
fig.tight_layout(); fig.savefig(FIG_DIR / "quality_gate_examples.png", dpi=130); plt.show()

"""Save"""

new = ["preprocessing_stages.png", "preprocessing_closeup.png", "preprocessing_variants.png",
       "preprocessing_histograms.png", "preprocessing_parameters.png", "preprocessing_standardisation.png",
       "quality_gate_examples.png"]
for f in new: print(f"figures/{f:40s} {'OK' if (FIG_DIR / f).exists() else 'MISSING'}")
for f in ["preprocessing_metrics.csv", "resolution_vs_grade.csv", "quality_thresholds.json", "quality_gate_rates.csv"]:
    print(f"{f:48s} {'OK' if (OUTPUT_DIR / f).exists() else 'MISSING'}")