# -*- coding: utf-8 -*-
"""phase4_model_transfer_learning_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQ2aKROG41ETvRwinPLBS5QMfRGD9y3t

CNN architecture, transfer learning and hyperparameter tuning

Check the GPU
"""

import tensorflow as tf
gpus = tf.config.list_physical_devices("GPU")
print("TensorFlow", tf.__version__, "| GPUs:", gpus)
if not gpus:
    raise SystemExit("No GPU. Runtime -> Change runtime type -> T4 GPU, then run again.")
!nvidia-smi --query-gpu=name,memory.total --format=csv

"""Connect Google Drive"""

from google.colab import drive
drive.mount("/content/drive")
from pathlib import Path
PROJECT_DIR = Path("/content/drive/MyDrive/CV-CW")
OUTPUT_DIR = PROJECT_DIR / "outputs"; FIG_DIR = OUTPUT_DIR / "figures"
for f in ["splits.csv", "quality_thresholds.json"]:
    print(f"{f:26s} found: {(OUTPUT_DIR / f).exists()}")

"""Load the project code

"""

import sys, zipfile, shutil
CODE_ZIP = PROJECT_DIR / "project.zip"
if Path("/content/project").exists():
    shutil.rmtree("/content/project")
with zipfile.ZipFile(CODE_ZIP) as z:
    z.extractall("/content")
SRC = Path("/content/project/src")
sys.path.insert(0, str(SRC))
assert "--dropout" in (SRC / "train.py").read_text(), "Old project.zip - upload the latest one to Drive"
print("Code ready:", sorted(p.name for p in SRC.glob("*.py")))

"""Unpack the images"""

IMG_DIR = Path("/content/aptos_1024/images")
if not any(IMG_DIR.glob("*.jpg")):
    shutil.copy(PROJECT_DIR / "aptos_1024.zip", "/content/aptos_1024.zip")
    with zipfile.ZipFile("/content/aptos_1024.zip") as z:
        z.extractall("/content/aptos_1024")
print("images on disk:", len(list(IMG_DIR.glob("*.jpg"))))

import json, time, subprocess
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from IPython.display import Image, display
import config
from preprocess import load_splits, cache_dataframe

print("environment:", config.ENVIRONMENT, "| outputs:", config.OUTPUT_DIR, "| cache:", config.CACHE_DIR)
splits = load_splits()
print(splits.groupby("split").size().to_dict(), "| images found:",
      splits.path.map(lambda p: Path(p).exists()).mean() * 100, "%")

EXP_CSV = config.OUTPUT_DIR / "experiments.csv"
VARIANT, AUG, BALANCE = "P2_clahe_unsharp", "standard", "both"
EPOCHS_HEAD, EPOCHS_FT = 3, 12
NOISE = 0.01
EXTRA_ARGS = ""

"""The architecture

Every candidate network gets the same **head** on top of its pretrained **backbone**:

```
image ─► backbone (ImageNet weights) ─► feature map ─┬─► global AVERAGE pool ─┐
                                                     └─► global MAX pool ─────┴─► concat
      ─► BatchNorm ─► Dropout ─► Dense(256, swish) ─► Dropout ─┬─► stage: 5-class softmax
                                                               └─► referable: sigmoid (grade ≥ 2)
```


"""

import keras
from model import build_model, set_backbone_trainable, count_params

rows = []
for bb, spec in config.BACKBONES.items():
    m, layers, gl = build_model(bb, spec["size"], pretrained=True)
    set_backbone_trainable(m, layers, 0.0);                 p1 = count_params(m)["trainable_params"]
    set_backbone_trainable(m, layers, config.UNFREEZE_FRACTION); p2 = count_params(m)["trainable_params"]
    rows.append({"backbone": bb, "input": f"{spec['size']}x{spec['size']}", "backbone_layers": len(layers),
                 "total_params_M": round(count_params(m)["total_params"] / 1e6, 2),
                 "trainable_phase1_M": round(p1 / 1e6, 2), "trainable_phase2_M": round(p2 / 1e6, 2),
                 "gradcam_layer": gl})
    if bb == "efficientnet_b0":
        head_start = [l.name for l in m.layers].index("dual_pool") - 2
        head = pd.DataFrame([{"layer": l.name, "type": type(l).__name__,
                              "output shape": str(tuple(l.output.shape) if not isinstance(l.output, dict) else "-"),
                              "parameters": l.count_params()} for l in m.layers[head_start:]])
    del m; keras.backend.clear_session()
candidates = pd.DataFrame(rows)
candidates.to_csv(config.OUTPUT_DIR / "backbone_candidates.csv", index=False)
head.to_csv(config.OUTPUT_DIR / "model_head_summary.csv", index=False)
display(candidates); display(head)

"""runs each experiment using two-stage transfer learning, first training the new model head and then carefully fine-tuning part of the pretrained model, while using validation QWK and confidence intervals to compare the runs fairly."""

def done_runs():
    return set(pd.read_csv(EXP_CSV).run_name) if EXP_CSV.exists() else set()

def run(name, **overrides):
    """Train one configuration with src/train.py, unless it already finished (resumable)."""
    if name in done_runs():
        print(f"✓ {name} already done - skipped"); return
    args = {"backbone": "efficientnet_b0", "variant": VARIANT, "aug": AUG, "balance": BALANCE,
            "epochs_head": EPOCHS_HEAD, "epochs_ft": EPOCHS_FT, **overrides}
    flags = " ".join(f"--{k} {v}" for k, v in args.items())
    print(f"▶ {name}: {flags}")
    t0 = time.time()
    get_ipython().system(f"cd {SRC} && python train.py {flags} --mixed_precision --run_name {name} {EXTRA_ARGS} 2>&1 | grep -v -E 'oneDNN|cuda_|absl|computation placer|TF-TRT|cpu_feature'")
    if name in done_runs():
        print(f"  finished in {(time.time() - t0) / 60:.1f} min")
    else:
        print(f"  ⚠ {name} did not finish - scroll up for the error message")

def results(prefix):
    exp = pd.read_csv(EXP_CSV)
    return exp[exp.run_name.str.startswith(prefix)].drop_duplicates("run_name", keep="last").reset_index(drop=True)

# Pre-process the images once for both input sizes (deterministic, ~1 min each)
for size in sorted({s["size"] for s in config.BACKBONES.values()}):
    t0 = time.time(); cache_dataframe(splits, VARIANT, size)
    print(f"{VARIANT} at {size}px cached in {time.time() - t0:.0f}s")

"""compares five pretrained CNN models using exactly the same settings to see how their architectures affect performance, while also considering model size and speed."""

BENCHMARK = ["efficientnet_b0", "mobilenetv3_large", "resnet50v2", "densenet121", "efficientnet_b3"]
for bb in BENCHMARK:
    run(f"bench_{bb}", backbone=bb)

"""compares the five models using their validation QWK scores and chooses the best-performing model, unless a smaller model is almost as good (within 0.01 QWK)."""

bench = results("bench_")
bench["params_M"] = (bench.total_params / 1e6).round(1)
cols = ["backbone", "size", "params_M", "val_qwk", "val_qwk_ci_low", "val_qwk_ci_high", "val_macro_f1",
        "val_accuracy", "train_val_acc_gap", "best_epoch", "train_minutes", "ms_per_image"]
bench = bench[cols].sort_values("val_qwk", ascending=False).reset_index(drop=True)
bench.to_csv(config.OUTPUT_DIR / "backbone_benchmark.csv", index=False)
display(bench)

fig, axes = plt.subplots(1, 2, figsize=(14, 4.4))
err = [bench.val_qwk - bench.val_qwk_ci_low, bench.val_qwk_ci_high - bench.val_qwk]
axes[0].barh(bench.backbone, bench.val_qwk, xerr=err, color="#2b6f8e", capsize=4)
axes[0].set(xlabel="validation QWK (bars: 95% bootstrap CI)", xlim=(max(0, bench.val_qwk_ci_low.min() - 0.05), 1),
            title="Accuracy of each pretrained backbone"); axes[0].invert_yaxis()
axes[1].scatter(bench.ms_per_image, bench.val_qwk, s=bench.params_M * 12, alpha=0.6, c="#b03a2e")
for _, r in bench.iterrows():
    axes[1].annotate(f"{r.backbone}\n{r.params_M}M", (r.ms_per_image, r.val_qwk), fontsize=8,
                     xytext=(6, -4), textcoords="offset points")
axes[1].set(xlabel="inference time per image on the T4 GPU (ms)", ylabel="validation QWK",
            title="Accuracy vs speed (bubble size = parameters)")
fig.tight_layout(); fig.savefig(FIG_DIR / "backbone_benchmark.png", dpi=150); plt.show()

best = bench.iloc[0]
ties = bench[bench.val_qwk >= best.val_qwk - NOISE]
suggest = ties.sort_values("params_M").iloc[0]
print(f"Highest QWK: {best.backbone} ({best.val_qwk:.3f}, CI {best.val_qwk_ci_low:.3f}-{best.val_qwk_ci_high:.3f})")
print(f"Suggested by the choosing rule: {suggest.backbone} ({suggest.params_M}M parameters, QWK {suggest.val_qwk:.3f})")

# Training curves of the suggested backbone: the dashed line marks where fine-tuning starts
display(Image(str(config.RUNS_DIR / f"bench_{suggest.backbone}" / "curves.png"), width=1100))

"""Hyperparameter tuning"""

def choose(stage, key, default):
    """Highest QWK wins, but the default is kept unless beaten by at least NOISE."""
    top = stage.sort_values("val_qwk", ascending=False).iloc[0]
    base = stage[stage[key] == default].iloc[0]
    return float(top[key]) if top.val_qwk - base.val_qwk >= NOISE else float(default)

# The benchmark B0 run (lr 1e-4, unfreeze 0.3, dropout 0.4) is the shared starting point
b0 = results("bench_efficientnet_b0")
assert len(b0), "Run step 4 first"

# Stage 1 - fine-tuning learning rate
for lr in [3e-5, 3e-4]:
    run(f"tune_lr_{lr:g}", lr_ft=lr)
stage1 = pd.concat([b0, results("tune_lr_")], ignore_index=True)
LR = choose(stage1, "lr_ft", 1e-4)
print("→ fine-tuning learning rate:", LR)

# Stage 2 - unfreezing depth, at the chosen learning rate
for uf in [0.6, 1.0]:
    run(f"tune_unfreeze_{uf:g}_lr_{LR:g}", lr_ft=LR, unfreeze=uf)
stage2 = pd.concat([stage1[np.isclose(stage1.lr_ft, LR)], results(f"tune_unfreeze_")
                    .query("lr_ft == @LR")], ignore_index=True)
UF = choose(stage2, "unfreeze", 0.3)
print("→ unfreeze fraction:", UF)

# Stage 3 - dropout, at the chosen learning rate and unfreezing
for dp in [0.2, 0.6]:
    run(f"tune_dropout_{dp:g}_uf_{UF:g}_lr_{LR:g}", lr_ft=LR, unfreeze=UF, dropout=dp)
stage3 = pd.concat([stage2[np.isclose(stage2.unfreeze, UF)], results("tune_dropout_")
                    .query("lr_ft == @LR and unfreeze == @UF")], ignore_index=True)
DROPOUT = choose(stage3, "dropout", 0.4)
print("→ dropout:", DROPOUT)

"""Tuning results"""

tuning = pd.concat([stage1.assign(stage="1 learning rate"), stage2.assign(stage="2 unfreeze"),
                    stage3.assign(stage="3 dropout")])
keep = ["stage", "run_name", "lr_ft", "unfreeze", "dropout", "val_qwk", "val_qwk_ci_low", "val_qwk_ci_high",
        "val_macro_f1", "train_val_acc_gap", "best_epoch"]
tuning = tuning[keep].reset_index(drop=True)
tuning.to_csv(config.OUTPUT_DIR / "tuning_results.csv", index=False)
display(tuning)

fig, axes = plt.subplots(1, 3, figsize=(15, 3.8), sharey=True)
for ax, (st, key, chosen, log) in zip(axes, [("1 learning rate", "lr_ft", LR, True),
                                            ("2 unfreeze", "unfreeze", UF, False),
                                            ("3 dropout", "dropout", DROPOUT, False)]):
    d = tuning[tuning.stage == st].sort_values(key)
    ax.errorbar(d[key], d.val_qwk, yerr=[d.val_qwk - d.val_qwk_ci_low, d.val_qwk_ci_high - d.val_qwk],
                fmt="o-", capsize=4, color="#2b6f8e")
    ax.axvline(chosen, ls=":", c="#b03a2e"); ax.set(xlabel=key, title=f"Stage {st}")
    if log: ax.set_xscale("log")
axes[0].set_ylabel("validation QWK (95% CI)")
fig.suptitle("One-at-a-time hyperparameter tuning on EfficientNet-B0 (dotted = chosen)", fontsize=11)
fig.tight_layout(); fig.savefig(FIG_DIR / "tuning_results.png", dpi=150); plt.show()

"""Record the choice for phase 5

"""

FINAL_BACKBONE = suggest.backbone          # change only if you have a reason, and write it down
choice = {"backbone": FINAL_BACKBONE, "size": int(config.BACKBONES[FINAL_BACKBONE]["size"]),
          "lr_ft": LR, "unfreeze": UF, "dropout": DROPOUT,
          "benchmark_qwk": float(bench.set_index("backbone").loc[FINAL_BACKBONE, "val_qwk"]),
          "tuning_proxy": "efficientnet_b0"}
json.dump(choice, open(config.OUTPUT_DIR / "phase4_choice.json", "w"), indent=2)
print(json.dumps(choice, indent=2))