# -*- coding: utf-8 -*-
"""phase3_augmentation_balancing_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cANNZ1qbTM_we-vqGd2O_Jbm-K_rBq9g

Data augmentation and class balancing

Connect Google Drive
"""

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
PROJECT_DIR = Path("/content/drive/MyDrive/CV-CW")
OUTPUT_DIR = PROJECT_DIR / "outputs"; FIG_DIR = OUTPUT_DIR / "figures"
WORKING_ZIP = PROJECT_DIR / "aptos_1024.zip"
print("splits.csv found:", (OUTPUT_DIR / "splits.csv").exists(), "| working copy found:", WORKING_ZIP.exists())

"""Unpack the working copy"""

import zipfile, shutil
IMG_DIR = Path("/content/aptos_1024/images")
if not any(IMG_DIR.glob("*.jpg")):
    shutil.copy(WORKING_ZIP, "/content/aptos_1024.zip")
    with zipfile.ZipFile("/content/aptos_1024.zip") as z:
        z.extractall("/content/aptos_1024")
print("images on disk:", len(list(IMG_DIR.glob("*.jpg"))))

"""loads the training data and applies the same preprocessing methods from Phase 2"""

import json, random
import numpy as np, pandas as pd, cv2
import matplotlib.pyplot as plt
import tensorflow as tf, keras
from sklearn.metrics import roc_auc_score

SEED = 42
random.seed(SEED); np.random.seed(SEED); tf.random.set_seed(SEED)
SIZE = 300
NUM_CLASSES = 5
CB_BETA = 0.999
CLASS_NAMES = ["No DR", "Mild NPDR", "Moderate NPDR", "Severe NPDR", "Proliferative DR"]
PREPROCESS_VARIANTS = {"P0_raw": "", "P1_clahe": "", "P2_clahe_unsharp": "", "P3_ben_graham": ""}
DEFAULT_VARIANT = "P2_clahe_unsharp"

print("TensorFlow", tf.__version__, "| Keras", keras.__version__)
assert hasattr(keras.layers, "RandomSharpness"), "Keras too old: run  !pip install -U keras  and restart"

splits = pd.read_csv(OUTPUT_DIR / "splits.csv")[["id", "grade", "split"]]
splits["img"] = splits["id"].map(lambda i: str(IMG_DIR / f"{i}.jpg"))
train = splits[splits.split == "train"].reset_index(drop=True)
print("training images:", len(train))

def load_rgb(path: str):
    """Read an image from disk as an RGB uint8 array."""
    bgr = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if bgr is None:
        raise FileNotFoundError(f"Could not read image: {path}")
    return cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)


def fov_mask(img: np.ndarray, tol: int = 10):
    """Binary mask of the circular field of view (pixels brighter than `tol`)."""
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    mask = (gray > tol).astype(np.uint8)
    # Morphological opening removes isolated bright specks in the border.
    return cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))


def crop_fov(img: np.ndarray, tol: int = 10):
    """Crop the black border so the retina touches the image edges."""
    mask = fov_mask(img, tol)
    ys, xs = np.where(mask > 0)
    if len(xs) < 0.05 * mask.size:      # almost-black image: do not crop
        return img
    return img[ys.min(): ys.max() + 1, xs.min(): xs.max() + 1]


def pad_to_square(img: np.ndarray):
    """Pad with black so width == height (keeps the retina circular)."""
    h, w = img.shape[:2]
    side = max(h, w)
    top, left = (side - h) // 2, (side - w) // 2
    return cv2.copyMakeBorder(img, top, side - h - top, left, side - w - left,
                              cv2.BORDER_CONSTANT, value=(0, 0, 0))


def circular_mask(img: np.ndarray, scale: float = 0.96):
    """Black out everything outside a centred circle (removes enhancement halo)."""
    h, w = img.shape[:2]
    mask = np.zeros((h, w), np.uint8)
    cv2.circle(mask, (w // 2, h // 2), int(min(h, w) / 2 * scale), 1, -1)
    return img * mask[..., None]


def clahe_lab(img: np.ndarray, clip: float = 2.0, grid: int = 8):
    """CLAHE on lightness only, so diagnostic colour is preserved."""
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    l = cv2.createCLAHE(clipLimit=clip, tileGridSize=(grid, grid)).apply(l)
    return cv2.cvtColor(cv2.merge((l, a, b)), cv2.COLOR_LAB2RGB)


def unsharp_mask(img: np.ndarray, sigma: float = 2.0, amount: float = 1.0):
    """Edge enhancement: img + amount * (img - blurred)."""
    blurred = cv2.GaussianBlur(img, (0, 0), sigma)
    return cv2.addWeighted(img, 1 + amount, blurred, -amount, 0)


def ben_graham(img: np.ndarray, sigma_ratio: float = 30.0):
    """Subtract the local average colour (Graham, 2015).

    4*I - 4*Gaussian(I) + 128 removes slow illumination changes between
    cameras and leaves lesions and vessels on a neutral grey background.
    """
    sigma = img.shape[0] / sigma_ratio
    return cv2.addWeighted(img, 4, cv2.GaussianBlur(img, (0, 0), sigma), -4, 128)


def preprocess(img: np.ndarray, variant: str = DEFAULT_VARIANT,
               size: int = 300):
    """Apply one named pre-processing variant and return a size x size RGB image."""
    if variant not in PREPROCESS_VARIANTS:
        raise ValueError(f"Unknown variant {variant}")
    out = pad_to_square(crop_fov(img))
    out = cv2.resize(out, (size, size), interpolation=cv2.INTER_AREA)

    if variant == "P1_clahe":
        out = clahe_lab(out)
    elif variant == "P2_clahe_unsharp":
        out = cv2.medianBlur(out, 3)
        out = clahe_lab(out)
        out = unsharp_mask(out)
    elif variant == "P3_ben_graham":
        out = ben_graham(out)
    return circular_mask(out)


def quality_metrics(img: np.ndarray):
    """Cheap, interpretable quality measures computed inside the field of view.

    sharpness  variance of the Laplacian of the green channel (low = blurred)
    brightness mean V (HSV) inside the FOV       (low = under-exposed)
    contrast   std of the green channel in FOV   (low = washed out)
    fov_ratio  share of the retina's bounding box that is retina: about 0.785
               (pi/4) for a complete circle, rising towards 1.0 when the camera
               cut the circle off; unusually low = irregular or partial retina
    The green channel is used because vessels and lesions have the highest
    contrast there. The cropped retina is resized straight to 512x512 (no
    padding) - exactly as in the phase 1 audit, so thresholds fitted on the
    phase 1 measurements apply unchanged to new photos in the app.
    """
    small = cv2.resize(crop_fov(img), (512, 512), interpolation=cv2.INTER_AREA)
    mask = fov_mask(small).astype(bool)
    if mask.sum() < 100:
        return {"sharpness": 0.0, "brightness": 0.0, "contrast": 0.0, "fov_ratio": 0.0}
    green = small[..., 1]
    lap = cv2.Laplacian(green, cv2.CV_64F)
    hsv = cv2.cvtColor(small, cv2.COLOR_RGB2HSV)
    return {
        "sharpness": float(lap[mask].var()),
        "brightness": float(hsv[..., 2][mask].mean()),
        "contrast": float(green[mask].std()),
        "fov_ratio": float(mask.mean()),
    }

"""realistic changes to training images"""

SHARPNESS_JITTER = (0.35, 0.65)

def _layers():
    """Keras is imported lazily so the audit/pre-processing scripts do not need it."""
    import tensorflow as tf
    from tensorflow import keras

    class RandomTranspose(keras.layers.Layer):
        """Swap height and width for a random half of the images. Together with
        RandomFlip this samples all 8 exact symmetries of a square (the dihedral
        group D4): no interpolation, so no blur."""

        def call(self, x, training=None):
            if not training:
                return x
            swap = tf.random.uniform([tf.shape(x)[0], 1, 1, 1]) < 0.5
            return tf.where(swap, tf.transpose(x, [0, 2, 1, 3]), x)

    class RetinaOnly(keras.layers.Layer):
        """Apply photometric layers to the retina only. Brightness shifts would
        otherwise lift the black background to grey, which never happens in a
        real pre-processed image."""

        def __init__(self, inner, **kwargs):
            super().__init__(**kwargs)
            self.inner = keras.Sequential(inner)

        def call(self, x, training=None):
            retina = tf.cast(tf.reduce_max(x, axis=-1, keepdims=True) > 5.0, x.dtype)
            return self.inner(x, training=training) * retina

    return keras, RandomTranspose, RetinaOnly


def build_augmenter(seed: int | None = SEED, shortcut_aware: bool = False):
    """Keras preprocessing layers; only active when called with training=True.

    shortcut_aware=True adds random sharpness jitter (Keras RandomSharpness).
    """
    keras, RandomTranspose, RetinaOnly = _layers()
    L = keras.layers
    photometric = [
        L.RandomBrightness(0.1, value_range=(0, 255), seed=seed),
        L.RandomContrast(0.1, seed=seed),
    ]
    if shortcut_aware:
        if not hasattr(L, "RandomSharpness"):
            raise ImportError("keras.layers.RandomSharpness needs Keras >= 3.8: pip install -U keras")
        photometric.append(L.RandomSharpness(factor=SHARPNESS_JITTER, value_range=(0, 255), seed=seed))
    name = "shortcut_aware_augmentation" if shortcut_aware else "fundus_safe_augmentation"
    return keras.Sequential([
        L.RandomFlip("horizontal_and_vertical", seed=seed),
        RandomTranspose(name="random_transpose"),
        RetinaOnly(photometric, name="retina_only_photometric"),
    ], name=name)


standard_aug = build_augmenter(seed=SEED)
shortcut_aug = build_augmenter(seed=SEED, shortcut_aware=True)
print([l.name for l in shortcut_aug.layers])
_, RandomTranspose, RetinaOnly = _layers()

"""eye image with 11 different augmentations"""

quality = pd.read_csv(OUTPUT_DIR / "image_quality.csv")[["id", "sharpness"]]
mod = train.merge(quality, on="id").query("grade == 2")
example = mod.iloc[(mod.sharpness - mod.sharpness.median()).abs().argsort().iloc[0]]
base = preprocess(load_rgb(example["img"]), DEFAULT_VARIANT, SIZE).astype("float32")

batch = shortcut_aug(tf.repeat(base[None], 11, axis=0), training=True).numpy().clip(0, 255).astype("uint8")
fig, axes = plt.subplots(2, 6, figsize=(15, 5.4))
for ax, im, t in zip(axes.flat, [base.astype("uint8"), *batch], ["Input (P2)"] + [f"Aug {i}" for i in range(1, 12)]):
    ax.imshow(im); ax.set_title(t, fontsize=9); ax.axis("off")
fig.tight_layout(); fig.savefig(FIG_DIR / "augmentation_examples.png", dpi=130); plt.show()

"""each augmentation method separately"""

L = keras.layers
single = {
    "flip":             L.RandomFlip("horizontal_and_vertical"),
    "90° rotation":     keras.Sequential([L.RandomFlip("horizontal_and_vertical"), RandomTranspose()]),
    "brightness ±10%":  RetinaOnly([L.RandomBrightness(0.1, value_range=(0, 255))]),
    "contrast ±10%":    RetinaOnly([L.RandomContrast(0.1)]),
    "sharpness jitter": RetinaOnly([L.RandomSharpness(factor=SHARPNESS_JITTER, value_range=(0, 255))]),
}
fig, axes = plt.subplots(len(single), 5, figsize=(12, 2.5 * len(single)))
for r, (name, layer) in enumerate(single.items()):
    outs = layer(tf.repeat(base[None], 4, axis=0), training=True).numpy().clip(0, 255).astype("uint8")
    for c, im in enumerate([base.astype("uint8"), *outs]):
        axes[r, c].imshow(im); axes[r, c].axis("off")
    axes[r, 0].set_title("input", fontsize=8)
    axes[r, 0].text(-0.12, 0.5, name, transform=axes[r, 0].transAxes, rotation=90, va="center", ha="right")
fig.tight_layout(); fig.savefig(FIG_DIR / "augmentation_catalogue.png", dpi=110); plt.show()

"""rejects"""

sev = train[train.grade >= 3].sample(1, random_state=SEED).iloc[0]
img = preprocess(load_rgb(sev["img"]), DEFAULT_VARIANT, SIZE)
healthy = preprocess(load_rgb(train[train.grade == 0].sample(1, random_state=SEED).iloc[0]["img"]), DEFAULT_VARIANT, SIZE)

hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV); hsv[..., 0] = (hsv[..., 0].astype(int) + 35) % 180
hue = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB) * (img.max(2, keepdims=True) > 10)
cut = img.copy(); s0 = SIZE // 3; cut[s0:2*s0, s0:2*s0] = 0
shear = cv2.warpAffine(img, np.float32([[1, 0.45, -0.45 * SIZE / 2], [0, 1, 0]]), (SIZE, SIZE))
grey = cv2.cvtColor(cv2.cvtColor(img, cv2.COLOR_RGB2GRAY), cv2.COLOR_GRAY2RGB)
mix = (0.5 * img + 0.5 * healthy).astype("uint8")

panels = [(img, f"Original (grade {sev['grade']})"), (hue, "Hue shift"), (cut, "Cutout"),
          (shear, "Strong shear"), (grey, "Greyscale"), (mix, f"Mixup with grade 0")]
fig, axes = plt.subplots(1, 6, figsize=(16, 3.3))
for ax, (im, t) in zip(axes, panels):
    ax.imshow(im); ax.set_title(t, fontsize=10); ax.axis("off")
fig.suptitle("Rejected transforms: each one changes or destroys the evidence for the grade", fontsize=11)
fig.tight_layout(); fig.savefig(FIG_DIR / "augmentation_rejected.png", dpi=130); plt.show()

"""checking augmented images realistic by comparing"""

real_sample = train.sample(300, random_state=SEED)
real = np.stack([preprocess(load_rgb(p), DEFAULT_VARIANT, SIZE) for p in real_sample["img"]])
def augment_batches(x, aug):
    """Apply an augmenter in batches of 50 (keeps memory low on Colab)."""
    return np.concatenate([aug(x[i:i+50].astype("float32"), training=True).numpy()
                           for i in range(0, len(x), 50)]).clip(0, 255).astype("uint8")

augmented = augment_batches(real, shortcut_aug)
m_real = pd.DataFrame([quality_metrics(im) for im in real])
m_aug = pd.DataFrame([quality_metrics(im) for im in augmented])

rows = []
for col in ["brightness", "contrast", "sharpness"]:
    for name, m in [("real", m_real), ("augmented", m_aug)]:
        p = np.percentile(m[col], [1, 50, 99])
        rows.append({"measure": col, "set": name, "p1": p[0], "median": p[1], "p99": p[2]})
realism = pd.DataFrame(rows).round(1)
realism.to_csv(OUTPUT_DIR / "augmentation_realism.csv", index=False)
display(realism)

fig, axes = plt.subplots(1, 3, figsize=(14, 3.6))
for ax, col in zip(axes, ["brightness", "contrast", "sharpness"]):
    bins = np.linspace(min(m_real[col].min(), m_aug[col].min()), max(m_real[col].max(), m_aug[col].max()), 40)
    ax.hist(m_real[col], bins=bins, alpha=0.6, label="real"); ax.hist(m_aug[col], bins=bins, alpha=0.6, label="augmented")
    ax.set(title=col, xlabel=col); ax.legend()
fig.suptitle("Augmented images compared with real pre-processed images", fontsize=11)
fig.tight_layout(); fig.savefig(FIG_DIR / "augmentation_realism.png", dpi=150); plt.show()

"""compares sharpness after different rotation and zoom methods"""

geo_arbitrary = keras.Sequential([L.RandomRotation(0.5, fill_mode="constant", fill_value=0.0),
                                  L.RandomZoom((-0.1, 0.1), fill_mode="constant", fill_value=0.0)])
geo_exact = keras.Sequential([L.RandomFlip("horizontal_and_vertical"), RandomTranspose()])
def median_sharpness(x):
    return float(np.median([quality_metrics(im)["sharpness"] for im in x.clip(0, 255).astype("uint8")]))
base_s = median_sharpness(real)
resampling = pd.DataFrame([
    {"design": "no augmentation", "median_sharpness": base_s},
    {"design": "arbitrary rotation + zoom (bilinear)",
     "median_sharpness": median_sharpness(augment_batches(real, geo_arbitrary))},
    {"design": "8 exact symmetries (chosen)",
     "median_sharpness": median_sharpness(augment_batches(real, geo_exact))},
])
resampling["change_%"] = (100 * (resampling.median_sharpness / base_s - 1)).round(1)
resampling = resampling.round(1)
resampling.to_csv(OUTPUT_DIR / "augmentation_resampling.csv", index=False)
display(resampling)

fig, ax = plt.subplots(figsize=(8, 3))
ax.barh(resampling.design, resampling.median_sharpness, color=["#9aa5b1", "#c0504d", "#2b6f8e"])
for i, (v, c) in enumerate(zip(resampling.median_sharpness, resampling["change_%"])):
    ax.text(v, i, f"  {c:+.0f}%", va="center", fontsize=9)
ax.set(xlabel="median sharpness (higher = crisper)", title="Blur added by each geometric augmentation")
ax.invert_yaxis(); fig.tight_layout(); fig.savefig(FIG_DIR / "augmentation_resampling.png", dpi=150); plt.show()

"""augmentation reduces the shortcut of using image sharpness to predict the disease grade"""

sample = pd.concat([g.sample(min(100, len(g)), random_state=SEED)
                    for _, g in train.groupby("grade")]).reset_index(drop=True)
healthy_label = (sample.grade == 0).values
raws = [load_rgb(p) for p in sample["img"]]
p0 = np.stack([preprocess(im, "P0_raw", SIZE) for im in raws])
p2 = np.stack([preprocess(im, DEFAULT_VARIANT, SIZE) for im in raws])

conditions = {"P0 (no pre-processing)": p0, "P2": p2,
              "P2 + standard augmentation": augment_batches(p2, standard_aug),
              "P2 + shortcut-aware augmentation": augment_batches(p2, shortcut_aug)}
auc_rows = []
for name, images in conditions.items():
    sharp = np.array([quality_metrics(im)["sharpness"] for im in images])
    a = roc_auc_score(healthy_label, sharp)
    auc_rows.append({"condition": name, "sharpness_auc": a, "shortcut_strength": abs(a - 0.5)})
auc = pd.DataFrame(auc_rows).round(3)
auc.to_csv(OUTPUT_DIR / "shortcut_auc.csv", index=False)
display(auc)

fig, ax = plt.subplots(figsize=(8, 3.6))
ax.barh(auc.condition, auc.shortcut_strength, color=["#9aa5b1", "#5b8db8", "#2b6f8e", "#1b4f63"])
for i, (v, a) in enumerate(zip(auc.shortcut_strength, auc.sharpness_auc)):
    ax.text(v, i, f"  AUC {a:.3f}", va="center", fontsize=9)
ax.set(xlim=(0, max(0.3, auc.shortcut_strength.max() * 1.35)),
       xlabel="shortcut strength = |AUC − 0.5|   (0 = sharpness reveals nothing about the grade)")
ax.invert_yaxis(); fig.tight_layout(); fig.savefig(FIG_DIR / "shortcut_auc.png", dpi=150); plt.show()

"""Class balancing"""

def effective_number_weights(labels: np.ndarray, beta: float = CB_BETA,
                             num_classes: int = NUM_CLASSES):
    """Class-balanced weights (Cui et al., 2019).

    w_c = (1 - beta) / (1 - beta ** n_c), normalised to mean 1.
    Softer than inverse frequency: very rare classes are up-weighted but not
    so much that a handful of images dominates the gradient.
    """
    counts = np.bincount(labels, minlength=num_classes).astype(np.float64)
    counts = np.maximum(counts, 1)
    weights = (1.0 - beta) / (1.0 - np.power(beta, counts))
    return (weights / weights.mean()).astype(np.float32)


def class_weight_schemes(labels: np.ndarray, num_classes: int = NUM_CLASSES):
    """The three weighting schemes compared in phase 3, each normalised to mean 1."""
    counts = np.maximum(np.bincount(labels, minlength=num_classes).astype(np.float64), 1)
    inverse = 1.0 / counts
    sqrt_inverse = 1.0 / np.sqrt(counts)
    return {
        "none": np.ones(num_classes, np.float32),
        "inverse_frequency": (inverse / inverse.mean()).astype(np.float32),
        "sqrt_inverse": (sqrt_inverse / sqrt_inverse.mean()).astype(np.float32),
        "effective_number": effective_number_weights(labels, num_classes=num_classes),
    }


def oversample(df: pd.DataFrame, target_share: float = 0.5,
               seed: int = SEED):
    """Re-sample each minority grade (with replacement) until it has at least
    `target_share` x the majority count. Only ever applied to TRAIN data."""
    max_n = df["grade"].value_counts().max()
    parts = []
    for g, part in df.groupby("grade"):
        need = int(target_share * max_n) - len(part)
        parts.append(part)
        if need > 0:
            parts.append(part.sample(need, replace=True, random_state=seed + int(g)))
    return pd.concat(parts).sample(frac=1.0, random_state=seed).reset_index(drop=True)

labels = train.grade.values
counts = np.bincount(labels, minlength=NUM_CLASSES)
schemes = class_weight_schemes(labels)
weights_table = pd.DataFrame(schemes, index=CLASS_NAMES).round(3)
weights_table.insert(0, "train images", counts)
share = pd.DataFrame({k: counts * w / (counts * w).sum() for k, w in schemes.items()}, index=CLASS_NAMES)
display(weights_table)
display((share * 100).round(1).rename(columns=lambda c: f"{c} loss share %"))

oversampled = oversample(train)
over_counts = np.bincount(oversampled.grade.values, minlength=NUM_CLASSES)
display(pd.DataFrame({"before": counts, "after oversampling": over_counts}, index=CLASS_NAMES))

json.dump({"chosen": "effective_number", "beta": CB_BETA,
           "weights": {k: [round(float(x), 4) for x in v] for k, v in schemes.items()},
           "oversampled_counts": over_counts.tolist()},
          open(OUTPUT_DIR / "class_weights.json", "w"), indent=2)

fig, axes = plt.subplots(1, 2, figsize=(14, 4.6))
x = np.arange(NUM_CLASSES); wbar = 0.2
for i, (k, w) in enumerate(schemes.items()):
    axes[0].bar(x + (i - 1.5) * wbar, w, wbar, label=k)
axes[0].set(xticks=x, xticklabels=[c.replace(" ", "\n") for c in CLASS_NAMES], ylabel="weight per image",
            title="Weight given to each image of a grade"); axes[0].legend(fontsize=8)
bottom = np.zeros(len(schemes))
for c, name in enumerate(CLASS_NAMES):
    vals = share.loc[name].values * 100
    axes[1].barh(list(schemes), vals, left=bottom, label=name); bottom += vals
axes[1].axvline(20, ls=":", c="k", lw=1)
axes[1].set(xlabel="share of total loss (%)", title="How much each grade drives learning")
axes[1].legend(fontsize=8, loc="upper center", bbox_to_anchor=(0.5, -0.16), ncol=5); axes[1].invert_yaxis()
fig.tight_layout(); fig.savefig(FIG_DIR / "class_balance.png", dpi=150); plt.show()

"""Focal loss"""

p = np.linspace(0.01, 1, 200)
fig, ax = plt.subplots(figsize=(6.5, 4))
for g in [0, 1, 2, 5]:
    ax.plot(p, -(1 - p) ** g * np.log(p), label=f"γ = {g}" + (" (cross-entropy)" if g == 0 else "") + (" (chosen)" if g == 2 else ""))
ax.axvspan(0.6, 1.0, color="#e8f1f5", zorder=0); ax.text(0.62, 3.6, "easy, well-classified", fontsize=8)
ax.set(xlabel="probability given to the true grade (p)", ylabel="loss", ylim=(0, 4), title="Focal loss vs cross-entropy")
ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR / "focal_loss.png", dpi=150); plt.show()
for g in [0, 2]:
    print(f"γ={g}:  loss at p=0.9 -> {-(0.1**g)*np.log(0.9):.4f}   loss at p=0.3 -> {-(0.7**g)*np.log(0.3):.4f}")

new = ["augmentation_examples.png", "augmentation_catalogue.png", "augmentation_rejected.png",
       "augmentation_realism.png", "augmentation_resampling.png", "shortcut_auc.png",
       "class_balance.png", "focal_loss.png"]
for f in new: print(f"figures/{f:32s} {'OK' if (FIG_DIR / f).exists() else 'MISSING'}")
for f in ["augmentation_realism.csv", "augmentation_resampling.csv", "shortcut_auc.csv", "class_weights.json"]:
    print(f"{f:40s} {'OK' if (OUTPUT_DIR / f).exists() else 'MISSING'}")