# -*- coding: utf-8 -*-
"""phase7_app_deployment_colab_updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8oMaoqsWtVCes6BA4i0Kd75UZdHMM5B

The web app: quality gate v2 and the deployment
"""

!pip install -q fpdf2

from google.colab import drive
drive.mount("/content/drive")
from pathlib import Path
import sys, zipfile, shutil
PROJECT_DIR = Path("/content/drive/MyDrive/CV-CW")
OUTPUT_DIR = PROJECT_DIR / "outputs"; FIG_DIR = OUTPUT_DIR / "figures"

CODE_ZIP = next(p for p in [PROJECT_DIR / "project.zip", PROJECT_DIR / "dr-sight.zip"] if p.exists())
if Path("/content/code").exists():
    shutil.rmtree("/content/code")
with zipfile.ZipFile(CODE_ZIP) as z:
    z.extractall("/content/code")
ROOT = next(p.parent.parent for p in Path("/content/code").rglob("src/train.py"))
SRC = ROOT / "src"
sys.path.insert(0, str(SRC))
assert "clipped" in (SRC / "preprocess.py").read_text(), f"Old {CODE_ZIP.name} - upload the latest one"
print("Code ready from", CODE_ZIP.name)

IMG_DIR = Path("/content/aptos_1024/images")
if not any(IMG_DIR.glob("*.jpg")):
    shutil.copy(PROJECT_DIR / "aptos_1024.zip", "/content/aptos_1024.zip")
    with zipfile.ZipFile("/content/aptos_1024.zip") as z:
        z.extractall("/content/aptos_1024")
print("images on disk:", len(list(IMG_DIR.glob("*.jpg"))))

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import json, time
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from concurrent.futures import ThreadPoolExecutor
from IPython.display import Image, display
import config
from preprocess import load_splits, load_rgb, quality_metrics, fit_quality_thresholds, assess_quality

MODEL_RUN = "bench_densenet121"
meta = json.loads((config.RUNS_DIR / MODEL_RUN / "meta.json").read_text())
def show(path, width=1000):
    print("saved:", Path(path).relative_to(PROJECT_DIR)); display(Image(str(path), width=width))

splits = load_splits()
print(f"model: {meta['backbone']} | test QWK {meta['test_metrics']['qwk']} | "
      f"review threshold {meta['review_confidence']:.3f}")
print(splits.groupby("split").size().to_dict())

"""Two new quality measures"""

train_paths = splits.loc[splits.split == "train", "path"].tolist()
t0 = time.time()
with ThreadPoolExecutor(8) as pool:
    train_q = pd.DataFrame(list(pool.map(lambda p: quality_metrics(load_rgb(p)), train_paths)))
print(f"measured {len(train_q)} training photos in {(time.time() - t0) / 60:.1f} min")
display(train_q[["sharpness", "brightness", "contrast", "clipped", "noise"]].describe().round(3))

"""Fit the thresholds"""

thr = fit_quality_thresholds(train_q, pct=1.0)
old_thr = json.loads((OUTPUT_DIR / "quality_thresholds.json").read_text())
json.dump(thr, open(OUTPUT_DIR / "quality_thresholds.json", "w"), indent=2)
display(pd.DataFrame({"gate v1 (phase 2b)": pd.Series(old_thr), "gate v2 (now)": pd.Series(thr)}).round(4))

"""Does the new gate close the gap?"""

import robustness as rb
t0 = time.time()
cov_v2 = rb.gate_coverage(thr, n=200, progress=lambda s: None)
cov_v1 = rb.gate_coverage(old_thr, n=200, progress=lambda s: None)
print(f"done in {(time.time() - t0) / 60:.1f} min")

harm = pd.read_csv(config.OUTPUT_DIR / "evaluation" / "robustness.csv")[["corruption", "severity", "qwk"]]
gate = (cov_v1.rename(columns={"gate_refuses": "gate v1 refuses"})
        .merge(cov_v2.rename(columns={"gate_refuses": "gate v2 refuses", "main_reason": "v2 main reason"}),
               on=["corruption", "severity"]).merge(harm, on=["corruption", "severity"], how="left")
        .drop(columns=["main_reason"]))
gate.to_csv(config.OUTPUT_DIR / "evaluation" / "gate_v2_coverage.csv", index=False)
display(gate[gate.severity == 3][["corruption", "qwk", "gate v1 refuses", "gate v2 refuses", "v2 main reason"]])

worst = gate[gate.severity == 3].set_index("corruption")
fig, ax = plt.subplots(figsize=(10, 4.4))
x = np.arange(len(worst)); w = 0.38
ax.bar(x - w/2, worst["gate v1 refuses"] * 100, w, label="gate v1 (phases 2b–6)", color="#9aa5b1")
ax.bar(x + w/2, worst["gate v2 refuses"] * 100, w, label="gate v2 (+ clipping, noise)", color="#2b6f8e")
ax.set(xticks=x, xticklabels=[c.replace("_", "\n") for c in worst.index], ylabel="% refused at severity 3",
       title="Quality gate: which degraded photos are refused before grading")
ax.legend(); ax.grid(axis="y", alpha=.3)
fig.tight_layout(); fig.savefig(FIG_DIR / "eval_gate_v2.png", dpi=150); plt.show()
print("saved: outputs/figures/eval_gate_v2.png")

"""Does the new gate refuse real photos?"""

q_all = []
with ThreadPoolExecutor(8) as pool:
    q_all = pd.DataFrame(list(pool.map(lambda p: quality_metrics(load_rgb(p)), splits.path)))
q_all = pd.concat([splits.reset_index(drop=True), q_all], axis=1)
checks = {"blurred": q_all.sharpness < thr["sharpness_min"],
          "too dark": q_all.brightness < thr["brightness_min"],
          "low contrast": q_all.contrast < thr["contrast_min"],
          "over-exposed": q_all.clipped > thr["clipped_max"],
          "noisy": q_all.noise > thr["noise_max"]}
for k, v in checks.items(): q_all[k] = v
q_all["refused"] = np.any(np.column_stack(list(checks.values())), axis=1)
by_split = q_all.groupby("split")[["refused", *checks]].mean().mul(100).round(1)
by_grade = (q_all.groupby(q_all.grade.map(lambda g: config.CLASS_NAMES[g]))["refused"].mean()
            .reindex(config.CLASS_NAMES).mul(100).round(1).to_frame("refused (%)"))
pd.concat({"by split (%)": by_split["refused"], "by grade (%)": by_grade["refused (%)"]}).to_csv(
    OUTPUT_DIR / "quality_gate_rates.csv")
display(by_split); display(by_grade)

"""The app pipeline, end to end"""

from inference import DRPredictor, pdf_report
predictor = DRPredictor(config.RUNS_DIR / MODEL_RUN / "best.keras",
                        config.RUNS_DIR / MODEL_RUN / "meta.json",
                        OUTPUT_DIR / "quality_thresholds.json")
sample = splits.query("split == 'test' and grade >= 2").sample(1, random_state=config.SEED).iloc[0]
img = load_rgb(sample.path)
res = predictor.predict(img)
print(f"true grade {config.CLASS_NAMES[sample.grade]} -> predicted {res.get('grade_name', 'ungradable')} "
      f"({res.get('confidence', 0):.0%}) | triage {res.get('triage', '-')} | review: {res.get('needs_review')}")

fig, axes = plt.subplots(1, 3, figsize=(12, 4.2))
for ax, (im, t) in zip(axes, [(img, "uploaded"), (res["preprocessed"], "pre-processed"),
                              (res["gradcam"], "Grad-CAM")]):
    ax.imshow(im); ax.set_title(t, fontsize=10); ax.axis("off")
fig.suptitle(f"App pipeline on one test photo: {res['triage']} - {res['grade_name']}", fontsize=11)
fig.tight_layout(); fig.savefig(FIG_DIR / "app_pipeline_example.png", dpi=150); plt.show()
pdf_report(res, img, OUTPUT_DIR / "evaluation" / "example_report.pdf")
print("PDF summary written to outputs/evaluation/example_report.pdf")

"""Package the deployment folder"""

import subprocess
out = subprocess.run(["bash", "app/prepare_space.sh", str(OUTPUT_DIR), MODEL_RUN],
                     cwd=ROOT, capture_output=True, text=True)
print(out.stdout or out.stderr)
space = ROOT / "space"
zip_path = PROJECT_DIR / "CW-project_space.zip"
shutil.make_archive(str(zip_path.with_suffix("")), "zip", space)
print("Space contents:", sorted(p.name for p in space.iterdir()))
print(f"\nZipped to Drive: {zip_path.name} ({zip_path.stat().st_size / 1e6:.0f} MB)")
big = [p for p in space.rglob("*") if p.is_file() and p.stat().st_size > 100e6]
print("files over GitHub's 100 MB limit:", [p.name for p in big] or "none - safe to push")